[package]
name = "keygen"
version = "0.1.0"
authors = ["Xuming Zeng <xsznix@gmail.com>"]

[dependencies]
rand = "0.7.3"
getopts = "0.2.21"
lazy_static = "1.1.1"

[profile.dev]
opt-level = 3
debug = true
